---
title: "index"
author: "Charles Hendrickson"
date: "11/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Welcome

```{r}
# get libraries
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  bbest/clockify,
  dplyr, DT, ggplot2,
  quiet = TRUE)

# CHANGE THESE VARIABLES!
api_txt <- "~/Documents/eds211/clockify_api-key"
project_name <- "crcm-science"

# use API key to authenticate
CLOCKIFY_API_KEY <- readLines(api_txt)
set_api_key(CLOCKIFY_API_KEY)

# get data
d_times <- time_entries_all()
# table(d_times$project_name) # confirm project_name
d_times <- d_times %>%
  filter(
    project_name == !!project_name) %>%
  select(
    task_name, time_start, duration_hrs, 
    user_name, description) %>% 
  arrange(task_name, time_start)
```
## my-rad-team {.tabset}

### Overall

```{r}
# plot ALL
plot_burndown(
  d_times,
  beg = as.Date("2021-10-02"), # day before
  end = as.Date("2021-11-21"), # day after
  hrs = 20)

# table ALL
datatable(d_times)
```

### 1. Import

```{r}
task <- "1. Import"
d_task <- d_times %>% 
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-02"), # day before
  end = as.Date("2021-10-12"), # day after
  hrs = 10)

datatable(d_task)
```

